### ISSUE TITLE
Exception in UWP native compiled code

### ISSUE THREAD

**Issue by bezysoftware** [unitycontainer/unity#17]
I get following exception in an UWP app when I compile it in release mode (using native chain):

   at System.Linq.Expressions.Expression.CreateLambda(Type delegateType, Expression body, String name, Boolean tailCall, ReadOnlyCollection`1 parameters)
   at System.Linq.Expressions.Expression.Lambda(Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda(Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda(Expression body, ParameterExpression[] parameters)
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.GetBuildMethod()
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlanCreatorPolicy.CreatePlan(IBuilderContext context, NamedTypeBuildKey buildKey)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)

This happens when resolving a registered type.

**Comment by bezysoftware** [comment]
I tried a new solution, and it worked there. However once I copied everything over, I got the same error again. After some poking around, it got fixed by following line in my rd.xml

<Assembly Name="System.Linq.Expressions" Dynamic="Required All" />

**Comment by ENikS** [comment]
I guess all is well. Closing as solved.
