### ISSUE TITLE
Unity Exception

### ISSUE THREAD

**Issue by abadakhshan** [unitycontainer/unity#195]
hello
sometimes i get this exception on unity

I use this packages:

<package id="Unity" version="3.0.1304.1" targetFramework="net46" />
<package id="Unity.Mvc5" version="1.1" targetFramework="net46" />
<package id="Unity.WebAPI" version="5.1" targetFramework="net46" />

```
Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at Microsoft.Practices.Unity.UnityContainer.FillTypeRegistrationDictionary(IDictionary`2 typeRegistrations)
   at Microsoft.Practices.Unity.UnityContainer.FillTypeRegistrationDictionary(IDictionary`2 typeRegistrations)
   at Microsoft.Practices.Unity.UnityContainer.get_Registrations()
   at Microsoft.Practices.Unity.UnityContainerExtensions.IsRegistered(IUnityContainer container, Type typeToCheck, String nameToCheck)
   at Unity.Mvc5.UnityDependencyResolver.IsRegistered(Type typeToCheck)
   at Unity.Mvc5.UnityDependencyResolver.GetService(Type serviceType)
   at System.Web.Mvc.DependencyResolverExtensions.GetService[TService](IDependencyResolver resolver)
   at System.Web.Mvc.SingleServiceResolver`1.GetValueFromResolver()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at System.Web.Mvc.SingleServiceResolver`1.get_Current()
   at System.Web.Mvc.MvcRouteHandler.GetSessionStateBehavior(RequestContext requestContext)
   at System.Web.Mvc.MvcRouteHandler.GetHttpHandler(RequestContext requestContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by ENikS** [comment]
Could you provide a test case to replicate this error?

**Comment by ENikS** [comment]
I guess it is not relevant anymore
