### ISSUE TITLE
Resolution issue

### ISSUE THREAD

**Issue by Robelind** [unitycontainer/unity#199]
```
public interface IC {}
    
    class C : IC
    {
        public C(string str, D d) {}
    }

    class D
    {
    }

IUnityContainer container = new UnityContainer();

container.RegisterType<D>();
container.RegisterType<IC, C>(new InjectionFactory(c => new C("str", c.Resolve<D>())));

IC cc = container.Resolve<IC>();


```> Resolution of the dependency failed, type = 'BugRepro.IC', name = '(none)'.
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The type String cannot be constructed. You must configure the container to supply this value.
At the time of the exception, the container was: 
  Resolving BugRepro.C,(none) (mapped from BugRepro.IC, (none))
    Resolving BugRepro.C,(none)
    Resolving parameter 'str' of constructor BugRepro.C(System.String str, BugRepro.D d)
      Resolving System.String,(none)

`   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.Creation.DynamicMethodConstructorStrategy.GuardTypeIsNonPrimitive(IBuilderContext context)
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.Creation.DynamicMethodConstructorStrategy.PreBuildUp(IBuilderContext context)
   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)
   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlanCreatorPolicy.CreatePlan(IBuilderContext context, INamedType buildKey)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)
   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at Unity.ResolverPolicy.NamedTypeDependencyResolverPolicy.Resolve(IBuilderContext context)
   at lambda_method(Closure , IBuilderContext )
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)
   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at Unity.ObjectBuilder.Policies.ResolveBuildUpPolicy.BuildUp(IBuilderContext context)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)
   at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String nameToBuild, ResolverOverride[] resolverOverrides)`

**Comment by ENikS** [comment]
Duplicate #200

**Comment by justin-romano** [comment]
fuck unity

**Comment by luizfbicalho** [comment]
I was a huge fan of unity, used in all of my projects, but I lost faith in  unity when the configuration stopped working and it didn't work on aspnet core 3

**Comment by ENikS** [comment]
Gentlemen,

I think you are confusing me with Microsoft. For last three years I've been the only one who maintained this entire project with no support from any organization or community. I spent my own time and money on tools, updates and fixing bugs. 

Instead of being upset waiting for the fix, you could help by contributing time or money to expedite process. The source code is all up here.
