### ISSUE TITLE
RegisterType<TInterface, TConcrete> does not work in combination with InjectionFactory

### ISSUE THREAD

**Issue by tsimbalar** [unitycontainer/unity#201]
Hi,

I'm seeing the following issue : `Resolve<TInterface>()` fails when the type mapping has been registered as 
```
container.RegisterType<TInterface,TClass>(new InjectionFactory(c=> new MyClass()));
```

but not when I call it with only one tpe parameter

I am pretty sure this worked with Nuget package Unity v4.0.1.
I am now using :
- Unity.Abstractions v3.2.0
- Unity.Container" v5.6.1

Target framework is .NET 4.6.2.

Here is a test case that allows to reproduce the issue : 

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Unity;
using Unity.Injection;

namespace Repro.Tests
{
    interface IMyInterface
    {
    }

    class MyImplementation : IMyInterface
    {
        public MyImplementation(string greeting)
        {
        }
    }

    [TestClass]
    public class Class1
    {
        // v This test fails v
        [TestMethod]
        public void Can_Resolve_Type_Registered_with_Injection_factory_and_2_type_parameters()
        {
            // Arrange		
            var container = new UnityContainer();
            container.RegisterType<IMyInterface, MyImplementation>(new InjectionFactory(c => new MyImplementation("Hello there")));

            // Act
            var impl = container.Resolve<IMyInterface>();

            // this throws : 
            //Unity.Exceptions.ResolutionFailedException: Resolution of the dependency failed, type = 'Repro.Tests.IMyInterface', name = '(none)'.
            //Exception occurred while: while resolving.
            //Exception is: InvalidOperationException - The type String cannot be constructed. You must configure the container to supply this value.
            //-----------------------------------------------
            //At the time of the exception, the container was: 
            //  Resolving Repro.Tests.MyImplementation,(none) (mapped from Repro.Tests.IMyInterface, (none))
            //    Resolving Repro.Tests.MyImplementation,(none)
            //    Resolving parameter 'greeting' of constructor Repro.Tests.MyImplementation(System.String greeting)
            //      Resolving System.String,(none)
            // ---> System.InvalidOperationException: The type String cannot be constructed. You must configure the container to supply this value.
            //   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.Creation.DynamicMethodConstructorStrategy.GuardTypeIsNonPrimitive(IBuilderContext context)
            //   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.Creation.DynamicMethodConstructorStrategy.PreBuildUp(IBuilderContext context)
            //   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)
            //   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)
            //   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlanCreatorPolicy.CreatePlan(IBuilderContext context, INamedType buildKey)
            //   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
            //   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)
            //   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)
            //   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
            //   at Unity.ResolverPolicy.NamedTypeDependencyResolverPolicy.Resolve(IBuilderContext context)
            //   at lambda_method(Closure , IBuilderContext )
            //   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
            //   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
            //   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
            //   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)
            //   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(IBuildPlanPolicy policy, IBuilderContext context)
            //   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
            //   at Unity.ObjectBuilder.Policies.ResolveBuildUpPolicy.BuildUp(IBuilderContext context)
            //   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
            //   at Unity.Container.StrategyChain.BuildUp(IBuilderContext builderContext)
            //   at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String nameToBuild, ResolverOverride[] resolverOverrides)
            //   --- End of inner exception stack trace ---
            //   at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String nameToBuild, ResolverOverride[] resolverOverrides)
            //   at Unity.UnityContainer.Resolve(Type type, String name, ResolverOverride[] resolverOverrides)
            //   at Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
            //   at Repro.Tests.Class1.Can_Resolve_Type_Registered_with_Injection_factory_and_2_type_parameters()
        }

        // v this test passes v
        [TestMethod]
        public void Can_Resolve_Type_Registered_with_Injection_factory_and_1_type_parameter()
        {
            // Arrange		
            var container = new UnityContainer();
            container.RegisterType<IMyInterface>(new InjectionFactory(c => new MyImplementation("Hello there")));

            // Act
            var impl = container.Resolve<IMyInterface>();

            // Assert
            Assert.IsInstanceOfType(impl, typeof(MyImplementation));
        }
    }
}

```

**Comment by trystesire** [comment]
Have you read the docs?

**Comment by ENikS** [comment]
Duplicace #199  #200  [#41](https://github.com/unitycontainer/abstractions/issues/41#event-1489100455)

**Comment by tsimbalar** [comment]
I have seen the release notes here, and I now believe it works as intended : https://github.com/unitycontainer/unity/releases/tag/5.2.1.311 

it states : 

> More strict use of InjectionFactory
> 
> This form of registration used to work for registering interface with InjectionFactory but it is no longer allowed.
> 
> RegisterType<IService, Service>(new InjectionFactory(c => new Service()));
> 
> As written, this code registers both: a mapping between IService and Service and between IService and InjectionFactory. These two are mutually exclusive and create ambiguity which Unity can not resolve.
> It should be either one of these but not both:
> 
> RegisterType<IService, Service>();
> RegisterType<IService>(new InjectionFactory(c => new Service()));

I still believe the change should be more obvious, as it may now introduce very subtle bugs in the apps ...

It would be better to actually throw a clear "NotSupportedException" or "InvalidOperationException" when calling the `RegisterType<T1, T2>()` with an `InjectionFactory` parameter.

**Comment by ENikS** [comment]
It should throw an exception when registering ``RegisterType<IService, Service>(new InjectionFactory(c => new Service()));``.  Does it not?

**Comment by tsimbalar** [comment]
No it does not (see my repro above)

It throws only at Resolve

**Comment by ENikS** [comment]
It did in 5.5.x

**Comment by ENikS** [comment]
Should be fixed for good once [this](https://github.com/unitycontainer/unity/issues/191) change is implemented

**Comment by tsimbalar** [comment]
I believe the regression was introduced by this commit : https://github.com/unitycontainer/container/commit/961d68a9255e55c1b373c8827b5bb9e7b085964b 

before that, there was : 

https://github.com/unitycontainer/container/blob/7b1f3108dab841ab3b899389f7c03a2376adbddf/src/UnityContainer.cs#L84-L89

... and now there is : 

https://github.com/unitycontainer/container/blob/cb1e24e981941ba4a924461df8aa2a35e7c1961a/src/UnityContainer.Registration.cs#L79-L82

**Comment by ENikS** [comment]
You are right. I've got the fix, will check in in a few.

**Comment by tsimbalar** [comment]
Thanks for the the reactivity !  🥇

**Comment by hogan** [comment]
At first I thought "oh no, what am I going to do". But then I realised that second generic parameter is not really needed.

On other hand, instead of exception, the second generic parameter can be used for explicit ensuring that injection factory returns expected type, for type checking.
