### ISSUE TITLE
Regression after updating the version to 5.8.6

### ISSUE THREAD

**Issue by godrose** [unitycontainer/unity#229]
I recently updated the version from `5.3.2` to `5.8.6`.
The following tests started to fail:
```
[Fact]
void RegisterTransientExplicitTypesWithDependencyCreator_ReturnsSameObjectsForTwoResolutions()
{
    var container = new UnityContainerAdapter();
            container.RegisterSingleton(typeof(ITestDependency), typeof(TestDependencyA), () => new TestDependencyA());

            var firstResolution = container.Resolve<ITestDependency>();
            var secondResolution = container.Resolve<ITestDependency>();
            firstResolution.Should().BeSameAs(secondResolution);
}

[Fact]
void  RegisterTransientExplicitTypesWithDependencyCreator_ReturnsTwoDifferentObjectsForTwoResolutions()
        {
            var container = new UnityContainerAdapter();
            container.RegisterTransient(typeof(ITestDependency), typeof(TestDependencyA), () => new TestDependencyA());

            var firstResolution = container.Resolve<ITestDependency>();
            var secondResolution = container.Resolve<ITestDependency>();
            firstResolution.Should().NotBeSameAs(secondResolution);
        }

public void RegisterSingleton(Type serviceType, Type implementationType, Func<object> dependencyCreator)
        {
            _container.RegisterType(serviceType, implementationType, new ContainerControlledLifetimeManager(),
                new InjectionFactory(context => dependencyCreator()));
        }

 public void RegisterTransient(Type serviceType, Type implementationType, Func<object> dependencyCreator)
        {
            _container.RegisterType(serviceType, implementationType,
                new InjectionFactory(context => dependencyCreator()));
        }
```
Both fail with the same exception:
`System.InvalidOperationException
Registration where both MappedToType and InjectionFactory are set is not supported
   at Unity.Registration.ContainerRegistration.Set(Type policyInterface, IBuilderPolicy policy)
   at Unity.UnityContainer.RegisterType(Type typeFrom, Type typeTo, String name, LifetimeManager lifetimeManager, InjectionMember[] injectionMembers)
   at Unity.UnityContainerExtensions.RegisterType(IUnityContainer container, Type from, Type to, LifetimeManager lifetimeManager, InjectionMember[] injectionMembers)`

This is a regression as a was able to use this functionality in the previous versions

**Comment by ENikS** [comment]
Duplicace #199  #200  [#41](https://github.com/unitycontainer/abstractions/issues/41#event-1489100455)
