### ISSUE TITLE
Registration name is ignored when parameterized InjectionConstructor is used

### ISSUE THREAD

**Issue by smoerijf** [unitycontainer/unity#300]
### Description
Since version 5.9.0 (v5.10.3 has still this issue) the name of a registration is ignored if the InjectionConstructor has parameters. v5.8.13 the provided unit tests run fine.

### To Reproduce
```C#
namespace Tests
{
    using System;
    using NUnit.Framework;
    using Unity;
    using Unity.Lifetime;
    using Unity.Resolution;
    using Unity.Injection;

    [TestFixture]
    public class IoContainerTests
    {
        private IUnityContainer container;

        private interface IMyTestInterface { }

        public class MyDefaultTestClass : IMyTestInterface
        {
            public MyDefaultTestClass() { }
            public MyDefaultTestClass(int i) { }
        }

        public class MyOtherTestClass : IMyTestInterface
        {
            public MyOtherTestClass() { }
            public MyOtherTestClass(int i) { }
        }

        [SetUp]
        public void Setup()
        {
            this.container = new UnityContainer();
            this.Register(typeof(IMyTestInterface), typeof(MyDefaultTestClass), "Default", new InjectionConstructor());
            this.Register(typeof(IMyTestInterface), typeof(MyOtherTestClass), "Other", new InjectionConstructor());

            var args = new InjectionConstructor(typeof(int));
            this.Register(typeof(IMyTestInterface), typeof(MyDefaultTestClass), "Default_args", args);
            this.Register(typeof(IMyTestInterface), typeof(MyOtherTestClass), "Other_args", args);
        }

        [Test]
        public void NoNameTest()
        {
            Assert.Throws<ResolutionFailedException>(() => this.container.Resolve<IMyTestInterface>());
        }

        [Test]
        public void DefaultTest()
        {
            var instance = this.container.Resolve<IMyTestInterface>("Default");
            Assert.IsTrue(instance is MyDefaultTestClass, instance.ToString());
        }

        [Test]
        public void OtherTest()
        {
            var instance = this.container.Resolve<IMyTestInterface>("Other");
            Assert.IsTrue(instance is MyOtherTestClass, instance.ToString());
        }

        [Test]
        public void NoName_WithParamsTest()
        {
            Assert.Throws<ResolutionFailedException>(() => this.container.Resolve<IMyTestInterface>(new ParameterOverride("i", 1)));
        }

// THIS TEST FAILS because instance is resolved to an "MyOtherTestClass"
        [Test]
        public void Default_WithParamsTest()
        {
            var instance = this.container.Resolve<IMyTestInterface>("Default_args", new ParameterOverride("i", 1));
            Assert.IsTrue(instance is MyDefaultTestClass, instance.ToString());
        }

        [Test]
        public void Other_WithParamsTest()
        {
            var instance = this.container.Resolve<IMyTestInterface>("Other_args", new ParameterOverride("i", 1));
            Assert.IsTrue(instance is MyOtherTestClass, instance.ToString());
        }

        public void Register(Type interfaceOfImplementation, Type implementation, string name, InjectionConstructor injectionConstructor)
        {
            InjectionMember[] injectionMembers = new InjectionMember[0];
            if (injectionConstructor != null)
            {
                injectionMembers = new InjectionMember[] { injectionConstructor };
            }
            this.container.RegisterType(interfaceOfImplementation, implementation, name, new TransientLifetimeManager(), injectionMembers);
        }
    }
}
```

If I change the order of the named registrations, the other test fails. The last named registration is always used.
```C#
this.Register(typeof(IMyTestInterface), typeof(MyDefaultTestClass), "Default_args", args);
this.Register(typeof(IMyTestInterface), typeof(MyOtherTestClass), "Other_args", args);
```

**Comment by ENikS** [comment]
The problem is with how you use Injection Constructor:
```c#
           var args = new InjectionConstructor(typeof(int));
            this.Register(typeof(IMyTestInterface), typeof(MyDefaultTestClass), "Default_args", args);
            this.Register(typeof(IMyTestInterface), typeof(MyOtherTestClass), "Other_args", args);
```
Sharing an InjectionConstructor between registrations is not supported. If you run Unity in diagnostic mode it will throw this exception:
```
Test Name:	Default_WithParamsTest
Test FullName:	Unity.Tests.Issues.IoContainerTests.Default_WithParamsTest
Test Source:	C:\Unity Container\v6.x\Container\tests\Unity.Tests\Issues\IoContainerTests.cs : line 77
Test Outcome:	Failed
Test Duration:	0:00:00.1964433

Result StackTrace:	
at Unity.ConstructorDiagnostic.<>c.<.cctor>b__17_0(Type type, InjectionMember member) in C:\Unity Container\v6.x\Container\src\Pipeline\Constructor\ConstructorInjection.cs:line 15
   at Unity.Injection.InjectionMember`2.AddPolicies[TContext,TPolicySet](Type registeredType, Type mappedToType, String name, TPolicySet& policies) in C:\Unity Container\v6.x\Abstractions\src\Dependency\Injection\Abstracts\InjectionMember.cs:line 133
   at Unity.UnityContainer.Unity.IUnityContainer.RegisterType(Type typeFrom, Type typeTo, String name, ITypeLifetimeManager lifetimeManager, InjectionMember[] injectionMembers) in C:\Unity Container\v6.x\Container\src\UnityContainer\IUnityContainer.cs:line 61
--- End of inner exception stack trace ---
    at Unity.UnityContainer.Unity.IUnityContainer.RegisterType(Type typeFrom, Type typeTo, String name, ITypeLifetimeManager lifetimeManager, InjectionMember[] injectionMembers) in C:\Unity Container\v6.x\Container\src\UnityContainer\IUnityContainer.cs:line 90
   at Unity.UnityContainerExtensions.RegisterType(IUnityContainer container, Type from, Type to, String name, InjectionMember[] injectionMembers) in C:\Unity Container\v6.x\Abstractions\src\Extensions\Container\UnityContainer.cs:line 377
   at Unity.Tests.Issues.IoContainerTests.Setup() in C:\Unity Container\v6.x\Container\tests\Unity.Tests\Issues\IoContainerTests.cs:line 46
Result Message:	
Initialization method Unity.Tests.Issues.IoContainerTests.Setup threw exception. System.InvalidOperationException: Sharing an InjectionConstructor between registrations is not supported

  Error in:  RegisterType<IMyTestInterface,MyOtherTestClass>( 'Other_args', Invoke.Constructor(System.Int32))
 ---> System.InvalidOperationException: Sharing an InjectionConstructor between registrations is not supported.
```
