### ISSUE TITLE
Disposed containers are again getting called

### ISSUE THREAD

**Issue by gop1983** [unitycontainer/unity#321]
This issue is in version 5.11.3.

In my application i am using default implementation of containers and life time managers. Application level we have one single container and in that we multiple instances and classes registered. Some of the class are configured as singleton by having container lifetime manager passed through its constructor. This particular application as User authentication and when the application is logged to clear all used data,etc we are resetting the container by disposing it and creating a new one. All the instances and classes are registered again on the new instance of container including singleton instances. 

Now sometimes when we are getting instances of some of the classes we are seeing the Unity logic is trying to access the disposed container and getting following exception.

_Unity.ResolutionFailedException: Resolution failed with error: Cannot access a disposed object.
Object name: 'Container[0]'.

For more detailed information run Unity in debug mode: new UnityContainer(ModeFlags.Diagnostic) ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Container[0]'.
   at Unity.UnityContainer.<Dispose>b__59_0(Type type, String name, Type policyInterface)
   at Unity.Builder.BuilderContext.Get(Type type, String name, Type policyInterface)
   at Unity.Strategies.LifetimeStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.<>c.<.ctor>b__73_1(BuilderContext& context)
   --- End of inner exception stack trace ---
   at Unity.UnityContainer.<>c.<.ctor>b__73_1(BuilderContext& context)
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides)
   at Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)_

Tried having a root container and creating child containers per session. So Logout time child container is disposed and new child container is created. root container is kept intact. In this case as well it is observed that the disposed child container is used.

**Comment by ENikS** [comment]
I would need to see a test case to help you with this.
