### ISSUE TITLE
Registering a mapping with an unbound generic interface causes a ResolutionFailedException

### ISSUE THREAD

**Issue by Coding-Lambda** [unitycontainer/unity#356]
I'm currently playing around with MediatR together with Unity. When I'm trying to register a "catch-all" mapping with an unbound generic interface, I get a `ResolutionFailedException` when calling `container.ResolveAll()`.

I'm currently using the exact same code as in described in the issue https://github.com/unitycontainer/unity/issues/215#issuecomment-380443152 together with the proposed line to solve said issue in the linked comment.

With `container.EnableDiagnostics()` i get the the following exception:
```
Unity.ResolutionFailedException: The current type, UnityVarianceTest.Program+INotificationHandler`1[UnityVarianceTest.Program+MyNotification], is an interface and cannot be constructed. Are you missing a type mapping?
_____________________________________________________
Exception occurred while:

• while resolving:  INotificationHandler`1 registered with name: GenericHandler

• while resolving:  INotificationHandler`1[]
 ---> System.InvalidOperationException: The current type, UnityVarianceTest.Program+INotificationHandler`1[UnityVarianceTest.Program+MyNotification], is an interface and cannot be constructed. Are you missing a type mapping? ---> Unity.Exceptions.InvalidRegistrationException: Exception of type 'Unity.Exceptions.InvalidRegistrationException' was thrown.
   --- End of inner exception stack trace ---
   at Unity.Processors.ConstructorDiagnostic.<>c.<GetResolver>b__13_0(BuilderContext& c) in C:\projects\unity\Container\src\Processors\Constructor\ConstructorDiagnostic.cs:line 294
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c) in C:\projects\unity\Container\src\Processors\Abstracts\MemberProcessor.cs:line 162
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c) in C:\projects\unity\Container\src\Processors\Abstracts\MemberProcessor.cs:line 162
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c) in C:\projects\unity\Container\src\Processors\Abstracts\MemberProcessor.cs:line 162
   at Unity.UnityContainer.<>c__DisplayClass113_0.<OptimizingFactory>b__0(BuilderContext& c) in C:\projects\unity\Container\src\UnityContainer.Resolution.cs:line 288
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context) in C:\projects\unity\Container\src\Strategies\BuildPlanStrategy.cs:line 80
   at Unity.UnityContainer.ContextValidatingExecutePlan(BuilderStrategy[] chain, BuilderContext& context) in C:\projects\unity\Container\src\UnityContainer.Resolution.cs:line 487
   at Unity.Builder.BuilderContext.Resolve(Type type, String name, InternalRegistration registration) in C:\projects\unity\Container\src\Builder\Context\BuilderContext.cs:line 177
   at Unity.Builder.BuilderContext.Resolve(Type type, String name) in C:\projects\unity\Container\src\Builder\Context\BuilderContext.cs:line 44
   at Unity.UnityContainer.ResolveRegistrations[TElement](BuilderContext& context, RegistrationSet registrations) in C:\projects\unity\Container\src\UnityContainer.Resolution.cs:line 205
   at Unity.UnityContainer.ResolveArray[TElement](BuilderContext& context) in C:\projects\unity\Container\src\UnityContainer.Resolution.cs:line 198
   at Unity.Strategies.ArrayResolveStrategy.PreBuildUp(BuilderContext& context) in C:\projects\unity\Container\src\Strategies\ArrayResolveStrategy.cs:line 82
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context) in C:\projects\unity\Container\src\UnityContainer.Resolution.cs:line 399
   --- End of inner exception stack trace ---
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context) in C:\projects\unity\Container\src\UnityContainer.Resolution.cs:line 421
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides) in C:\projects\unity\Container\src\UnityContainer.IUnityContainer.cs:line 244
   at Unity.UnityContainerExtensions.Resolve(IUnityContainer container, Type t, ResolverOverride[] overrides) in C:\projects\unity\Abstractions\src\Extensions\Container\UnityContainer.cs:line 913
   at Unity.UnityContainerExtensions.ResolveAll(IUnityContainer container, Type type, ResolverOverride[] resolverOverrides) in C:\projects\unity\Abstractions\src\Extensions\Container\UnityContainer.cs:line 942
   at Unity.UnityContainerExtensions.ResolveAll[T](IUnityContainer container, ResolverOverride[] resolverOverrides) in C:\projects\unity\Abstractions\src\Extensions\Container\UnityContainer.cs:line 967
   at UnityVarianceTest.Program.Main(String[] args) in D:\Git\UnityVarianceTest\UnityVarianceTest\Program.cs:line 59
```

Did something change with support for unbound generics or is there another solution to register a "catch-all" mapping for a generic interface?

Thank you for your help.

**Comment by ENikS** [comment]
I would need a UnitTest that I could run to give you an intelligent answer.

**Comment by Coding-Lambda** [comment]
Would this help?

https://github.com/Coding-Lambda/UnityVarianceTest/blob/master/UnitTestProject.Tests/Tests.cs

**Comment by ENikS** [comment]
You register generic interface with non generic handler:

 [`container.RegisterType(typeof(INotificationHandler<>), typeof(GenericHandler), "GenericHandler")`](https://github.com/Coding-Lambda/UnityVarianceTest/blob/c80fe76722684415f4104469684dce6cd70d187a/UnitTestProject.Tests/Tests.cs#L21)

did you try running it like this: 

`container.RegisterType(typeof(INotificationHandler<>), typeof(GenericHandler<>), "GenericHandler")`

**Comment by Coding-Lambda** [comment]
This indeed solves the problem, thank you!
I was confused because I based my test code on your answer from https://github.com/unitycontainer/unity/issues/215#issuecomment-380443152

So if I understand the documentation on [registering generics](http://unitycontainer.org/tutorials/Composition/Generics/generics.html) correctly, then `TFrom` an `TTo` must either be both bound generics or both unbound generics (no mixing them)?

**Comment by ENikS** [comment]
Yes, that is correct

**Comment by Coding-Lambda** [comment]
Thank you very much for your help and time, cheers!
