### ISSUE TITLE
InvalidCastException - Unable to cast object of type 'Microsoft.Practices.ObjectBuilder2.RecoveryStack' to type 'System.Security.IPermission'

### ISSUE THREAD

**Issue by Jan-Magerl** [unitycontainer/unity#75]
Sometimes i get this Exception while resolving simple Objects from Unity.
The Exception is NOT reproduceable.
Every Time the Exception occors i get a different Callstack.
The Excetiption apperes every two Weeks and i have no clue how to fix it.

Recoverystack or IPermission are not used in my Code.

Can anybody Help?

```
InvalidCastException - Unable to cast object of type 'Microsoft.Practices.ObjectBuilder2.RecoveryStack' to type 'System.Security.IPermission'.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving*.CommandHandler,(none) (mapped from *.CommandHandler`1[*.Command], (none))
  Resolving parameter "serviceRequester" of constructor *.CommandHandler(*.NotificationManager notificationManager, *.ServiceRequester serviceRequester)
    Resolving *.ServiceRequester,(none) (mapped from *.ServiceRequester, (none))
    Resolving parameter "notificationConverter" of constructor *ServiceRequester(*.IConverter`2[[*.Notification, *.Interfaces, Version=1.11.115.0, Culture=neutral, PublicKeyToken=null],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=*]] notificationConverter, *.IWcfClient wcfClient)
      Resolving *.NotificationConverter,(none) (mapped from *.IConverter`2[*.typeNotification,System.String], (none))
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.Practices.ObjectBuilder2.RecoveryStack' to type 'System.Security.IPermission'.
   at System.Security.Util.XMLUtil.SecurityObjectToXmlString(Object ob)
   at System.Security.SecurityException.set_PermitOnlySetInstance(Object value)
   at System.Security.SecurityException..ctor(String message, Object deny, Object permitOnly, MethodInfo method, Object demanded, IPermission permThatFailed)
   at System.Security.FrameSecurityDescriptor.CheckSetDemand2(PermissionSet demandSet, PermissionSet& alteredDemandSet, RuntimeMethodHandleInternal rmh, Boolean fDeclarative)
   at System.Security.FrameSecurityDescriptor.CheckSetDemand(PermissionSet demandSet, PermissionSet& alteredDemandSet, RuntimeMethodHandleInternal rmh)
   at System.Security.SecurityRuntime.FrameDescSetHelper(FrameSecurityDescriptor secDesc, PermissionSet demandSet, PermissionSet& alteredDemandSet, RuntimeMethodHandleInternal rmh)
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.GetBuildMethod()
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlanCreatorPolicy.CreatePlan(IBuilderContext context, NamedTypeBuildKey buildKey)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp(NamedTypeBuildKey newBuildKey)
   at Microsoft.Practices.Unity.ObjectBuilder.NamedTypeDependencyResolverPolicy.Resolve(IBuilderContext context)
   at lambda_method(Closure , IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp(NamedTypeBuildKey newBuildKey)
   at Microsoft.Practices.Unity.ObjectBuilder.NamedTypeDependencyResolverPolicy.Resolve(IBuilderContext context)
   at lambda_method(Closure , IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   --- End of inner exception stack trace ---
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)
```

**Comment by ENikS** [comment]
I could not reproduce this error
